### ISSUE TITLE
Es sind nicht alle Farben im Profil

### ISSUE THREAD

**Issue by Hobo2k** [fablabnbg/VisiCut#1]
Im Profil zu den Gravier/Schneidsettings werden nicht alle Farben aufgeführt.
![2015-12-14_22h49_06](https://cloud.githubusercontent.com/assets/5597327/11795261/13b7c796-a2b6-11e5-8cc6-a746216759e7.png)
![2015-12-14_22h49_22](https://cloud.githubusercontent.com/assets/5597327/11795262/13bc219c-a2b6-11e5-9c38-4563594976b1.png)

**Comment by jnweiger** [comment]
Good catch. Thanks. 
The list is one entry per profile. Each profile should list *all* the colors that map to that profile.

**Comment by jnweiger** [comment]
Fixed upstream via https://github.com/t-oster/VisiCut/pull/319

**Comment by jnweiger** [comment]
Fixed upstream via https://github.com/t-oster/VisiCut/pull/319
