### ISSUE TITLE
Ruida driver: line colors in the display are random?

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/VisiCut#17]
I sent the same file 3 times withdiffernt speed settings.
Lines drawn on the display while cutting were sometimes red sometimes green. The original line color was black, which is correctly shown on the right hand part of the display.

The USB serial works perfectly well with purejavacomm too :-)

**Comment by kkaempf** [comment]
SVG colors are not preserved as VectorPart properties (:cry:), so I just assign colors from [a fixed table](https://github.com/fablabnbg/LibLaserCut/blob/thunderlaser/src/com/t_oster/liblasercut/drivers/ruida/Ruida.java#L70) to the various layers.

**Comment by kkaempf** [comment]
closing
