### ISSUE TITLE
Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native

### ISSUE THREAD

**Issue by kkaempf** [fablabnbg/VisiCut#19]
> Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
> 	at com.sun.jna.Native.initIDs(Native Method)
> 	at com.sun.jna.Native.<clinit>(Native.java:139)
> 	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:23)
> 	at jtermios.linux.JTermiosImpl.<clinit>(JTermiosImpl.java:71)
> 	at jtermios.JTermios.<clinit>(JTermios.java:289)
> 	at purejavacomm.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:101)
> 	at com.t_oster.liblasercut.drivers.ruida.Serial.open(Serial.java:49)
>

**Comment by kkaempf** [comment]
https://github.com/java-native-access/jna/issues/281#issuecomment-26410558 suggests running with `-Djna.nosys=true`

**Comment by kkaempf** [comment]
`-Djna.nosys=true` solves this issue for me.

**Comment by gabuMore** [comment]
Where I can found this setting -Djna.nosys=true????? o where should I put this?

**Comment by gabuMore** [comment]
> `-Djna.nosys=true` solves this issue for me.


Where I can found this setting -Djna.nosys=true????? o where should I put this?
