### ISSUE TITLE
Maximum use of RAM

### ISSUE THREAD

**Issue by Hobo2k** [fablabnbg/VisiCut#2]
Hi,

Is there a possibility to increase the maximum size of RAM like "-Xmx4096m".

Per default or per option, also by Inkscape Extension.

Thanks

**Comment by kkaempf** [comment]
You can't do this from within a program.

Two options

- change the system default. In openSUSE, you can do this in `/etc/java/java.conf`
- Replace `/usr/bin/visicut` with a script which calls `java -Xmx4096m ...`
