### ISSUE TITLE
Additional space is not honored when engraving

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/VisiCut#22]
Despite setting "Additional space per Raster lin..." to 60.0 there seems to be no effect when engraving.
The laser head stops and reverses exactly on the two extreme lines that I have drawn in the svg.

These lines are my workaround to get even engraving throughout the entire pattern.

I've packed up

-rw-r--r--  1 testy testy 23840 Mär 25 19:50 logo-engrave.svg
-rw-rw-rw-  1 testy testy  8432 Mär 25 19:41 logo-engrave.plf
-rw-rw-rw-  1 testy testy 52511 Mär 25 19:41 logo-engrave.rd

in a zip, because github is stupid: 
[logo-engrave.zip](https://github.com/fablabnbg/VisiCut/files/1845596/logo-engrave.zip)

Nice result 
![photo_2018-03-25_19-55-42](https://user-images.githubusercontent.com/1108546/37878310-52c794b6-3067-11e8-9f91-f2c77d502f0f.jpg)

Laser-settings used with this were:

![photo_2018-03-25_19-51-42](https://user-images.githubusercontent.com/1108546/37878236-f6c49e80-3065-11e8-8477-4f8260a804a6.jpg)

**Comment by jnweiger** [comment]
I had assumed the unit for "Additional space per Raster lin..." is mm. Maybe it is raster resolution?

**Comment by kkaempf** [comment]
Fixed by https://github.com/fablabnbg/LibLaserCut/pull/14
