### ISSUE TITLE
Engraving object must be at position (0,0)

### ISSUE THREAD

**Issue by mrlinux1** [fablabnbg/VisiCut#23]
When I have a engraving object in inkscape in the center of a defined page, open that in Visicut
and try to "engrave everything" I get an error saying "Error Exception: Raster Start X !=0"

![screenshot from 2018-03-25 20-40-40](https://user-images.githubusercontent.com/9421663/37878732-b92ca20e-306d-11e8-87bb-bf9a1939631f.png)

It doesn't matter whether I open the whole file in visicut or select only my engraving object.
If I move the object into the left upper corner everything works.
Here is my svg file:
[drache-schild_last.zip](https://github.com/fablabnbg/VisiCut/files/1845657/drache-schild_last.zip)

**Comment by jnweiger** [comment]
Does it work when you push the drawing in visicut into the top lefthand corner?

**Comment by kkaempf** [comment]
Confirmed :weary:

**Comment by kkaempf** [comment]
Fixed by https://github.com/fablabnbg/LibLaserCut/pull/13
