### ISSUE TITLE
ThunderLaser Nova 35: Network not Working (Windows 10)

### ISSUE THREAD

**Issue by Hobo2k** [fablabnbg/VisiCut#29]
VisiCut sendet ein UDP Paket an den Port 50200 mit folgendem UDP Payload:

**016de28b (HEX)**

Dann passiert laut Wireshark nix mehr: Also es kommt kein Paket vom Laser zurück und im VisiCut erscheint folgende Meldung:

`Fehler:`
`IOException: Response timeout in UdpStream`

**Comment by kkaempf** [comment]
Na, dann hat VisiCut ja recht. Wenn der Nova nicht antwortet, kann VisiCut nix machen.

Bitte mal Netzwerk überprüfen (lassen).
