### ISSUE TITLE
Cannot download settings

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/VisiCut#31]
The latest version of visicut 1.8-24.11-20180519jw-beta.
I've made new .visicut settings from scratch. Uploaded them to https://github.com/fablabnbg/visicut-settings then tried to use 'Empfohlene Einstellungen laden' -> Fablab Reguin Nürnberg
The following error message appears, no settings get loaded:
![grafik](https://user-images.githubusercontent.com/1108546/43233191-03fcd8fa-9075-11e8-9c73-c0f732cbce0b.png)

There are several error messages from visicut: 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.collections.TreeMapConverter (file:/usr/share/visicut/lib/xstream-1.4.3.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.converters.collections.TreeMapConverter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Can't load settings.
```

**Comment by jnweiger** [comment]
The issue seems independant of the selected lab. Only the example settings can be loaded.

**Comment by kkaempf** [comment]
You don't expect me to debug/fix arbitrary Java libraries (xstream-1.4.3.jar in this case), do you ?

**Comment by kkaempf** [comment]
http://x-stream.github.io/download.html shows 1.4.10 as latest version

**Comment by kkaempf** [comment]
http://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar to be exact.

**Comment by jnweiger** [comment]
seen with both openjdk-11 and openjdk-8 --
Thanks for the hint about xstream. Whatever that is...
Found in VisiCut/lib/xstream-1.4.3.jar -- updating to 1.4.10, to see what happens..-.

**Comment by jnweiger** [comment]
With 1.4.10, I get these messages (and it still does not work then):
<pre>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/testy/src/github/fablabnbg/VisiCut/dist/lib/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Security framework of XStream not initialized, XStream is probably vulnerable.
Security framework of XStream not initialized, XStream is probably vulnerable.
Security framework of XStream not initialized, XStream is probably vulnerable.
Security framework of XStream not initialized, XStream is probably vulnerable.
Security framework of XStream not initialized, XStream is probably vulnerable.
</pre>

**Comment by kkaempf** [comment]
You're barking up the wrong tree

**Comment by jnweiger** [comment]
Thanks Klaus for the hints so far. Switching to the bigger tree.

**Comment by jnweiger** [comment]
Here is a fix:
```
sudo apt-get update
sudo apt install ca-certificates-java  # 20180516ubuntu1~18.04.1 from bionic-updates/main
```
