### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by dercorn** [fablabnbg/VisiCut#5]
Mac OS X Sierra no longer supports Java below version 7.
Is a port to Java 7 planned?

**Comment by jnweiger** [comment]
No Java ports planned from my side. Maybe @t-oster knows about Mac OSX support

**Comment by t-oster** [comment]
It should compile and Run fine on Java 7.

**Comment by t-oster** [comment]
In fact our Travis build runs on Java 7 https://github.com/t-oster/VisiCut/blob/develop/.travis.yml and I think we recently dropped Java 6 Support, so i don't understand the question. Why do you think we need to port? Also i am pretty sure Java is upwards compatible

**Comment by kkaempf** [comment]
I tested Java 8, 9, and 10 without major issues. Closing.
