### ISSUE TITLE
Java-Runtime for Mac

### ISSUE THREAD

**Issue by DerMozart** [fablabnbg/VisiCut#9]
Can we compile Visicut, so that it wont need the old Java 6 runtime, but maybe something newer? Java 6 is not officially supported for newer Mac Sierra installations.

**Comment by jnweiger** [comment]
![photo_2018-01-21_14-24-03](https://user-images.githubusercontent.com/1108546/35194648-c44c6f40-feb6-11e7-8b3c-e7d7396b86a2.jpg)

seen on high sierra 10.15.2

**Comment by jnweiger** [comment]
We use a VisiCut.app/Contents/Info.plist with the following settings:
```
        <dict>
                <key>ClassPath</key>
                <array>
                        <string>$JAVAROOT/Visicut.jar</string>
                        <string>$JAVAROOT/lib</string>
                </array>
                <key>JVMVersion</key>
                <string>1.6+</string>
                <key>MainClass</key>
                <string>com.t_oster.visicut.gui.VisicutApp</string>
```

https://stackoverflow.com/questions/14806709/application-is-using-java-6-from-apple-instead-of-java-7-from-oracle-on-mac-os-x#15271448

has a hint, that changing the "1.6+" to something newer would not work. It seems apple wants us to change much more.

**Comment by jnweiger** [comment]
We are at openjdk 11 now.
